# Generated by Django 2.2.3 on 2019-08-14 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.CharField(default='a6c541cc891d4b0d8bb1fe9035e1f245', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('game_over', models.BooleanField(default=False)),
                ('state', models.TextField(default='{\n            "(1,1)": 0,"(1,2)": 0,"(1,3)": 0,"(1,4)": 0,"(1,5)": 0,"(1,6)": 0,"(1,7)": 0,"(1,8)": 0,\n            "(2,1)": 0,"(2,2)": 0,"(2,3)": 0,"(2,4)": 0,"(2,5)": 0,"(2,6)": 0,"(2,7)": 0,"(2,8)": 0,\n            "(3,1)": 0,"(3,2)": 0,"(3,3)": 0,"(3,4)": 0,"(3,5)": 0,"(3,6)": 0,"(3,7)": 0,"(3,8)": 0,\n            "(4,1)": 0,"(4,2)": 0,"(4,3)": 0,"(4,4)": 0,"(4,5)": 0,"(4,6)": 0,"(4,7)": 0,"(4,8)": 0,\n            "(5,1)": 0,"(5,2)": 0,"(5,3)": 0,"(5,4)": 0,"(5,5)": 0,"(5,6)": 0,"(5,7)": 0,"(5,8)": 0,\n            "(6,1)": 0,"(6,2)": 0,"(6,3)": 0,"(6,4)": 0,"(6,5)": 0,"(6,6)": 0,"(6,7)": 0,"(6,8)": 0,\n            "(7,1)": 0,"(7,2)": 0,"(7,3)": 0,"(7,4)": 0,"(7,5)": 0,"(7,6)": 0,"(7,7)": 0,"(7,8)": 0,\n            "(8,1)": 0,"(8,2)": 0,"(8,3)": 0,"(8,4)": 0,"(8,5)": 0,"(8,6)": 0,"(8,7)": 0,"(8,8)": 0\n    }')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('move_coordinates', models.CharField(max_length=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
