# Generated by Django 2.2.3 on 2019-08-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190810_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default='48fe0c0e9ebe47bda67c5e6ff8f8c24c', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
