# Generated by Django 2.2.3 on 2019-08-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190810_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default='38902305fc7f4a49a5e13b895e36c9c0', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
