# Generated by Django 2.2.3 on 2019-08-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190810_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default='3fd373b8abae45dd95141b99d60a2c02', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
