# Generated by Django 2.2.3 on 2019-08-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190810_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default='eb51a4fcf3584dc7bbfcb9ecbf2cd933', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_coordinates',
            field=models.CharField(max_length=15),
        ),
    ]
