# Generated by Django 2.2.3 on 2019-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190810_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default='4048b3eb514c461ba2b8153ba444d0b4', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
