# Generated by Django 2.2.3 on 2019-08-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20190813_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default='b147face68e74be49ac59bb790a4b3b0', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
